[project]
name = "qmt-gateway"
version = "0.1.0"
description = "Bridge QuantConnect Lean to a Windows QMT client"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "xtquant==250807.1.2",
]

[[tool.uv.index]]
name = "tencent"
url = "https://mirrors.cloud.tencent.com/pypi/simple"
default = true
